// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: runbooks.proto

package runbooks

import (
	terraform1 "github.com/hashicorp/terraform/internal/rpcapi/terraform1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StepStatus int32

const (
	StepStatus_STEP_STATUS_INVALID   StepStatus = 0
	StepStatus_STEP_STATUS_READY     StepStatus = 1
	StepStatus_STEP_STATUS_SKIPPED   StepStatus = 2
	StepStatus_STEP_STATUS_FAILED    StepStatus = 3
	StepStatus_STEP_STATUS_SUCCEEDED StepStatus = 4
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "STEP_STATUS_INVALID",
		1: "STEP_STATUS_READY",
		2: "STEP_STATUS_SKIPPED",
		3: "STEP_STATUS_FAILED",
		4: "STEP_STATUS_SUCCEEDED",
	}
	StepStatus_value = map[string]int32{
		"STEP_STATUS_INVALID":   0,
		"STEP_STATUS_READY":     1,
		"STEP_STATUS_SKIPPED":   2,
		"STEP_STATUS_FAILED":    3,
		"STEP_STATUS_SUCCEEDED": 4,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runbooks_proto_enumTypes[0].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_runbooks_proto_enumTypes[0]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{0}
}

type FindRunbookConfigurationSteps_Condition_OnFail int32

const (
	FindRunbookConfigurationSteps_Condition_ON_FAIL_INVALID FindRunbookConfigurationSteps_Condition_OnFail = 0
	FindRunbookConfigurationSteps_Condition_ON_FAIL_ERROR   FindRunbookConfigurationSteps_Condition_OnFail = 1
	FindRunbookConfigurationSteps_Condition_ON_FAIL_SKIP    FindRunbookConfigurationSteps_Condition_OnFail = 2
)

// Enum value maps for FindRunbookConfigurationSteps_Condition_OnFail.
var (
	FindRunbookConfigurationSteps_Condition_OnFail_name = map[int32]string{
		0: "ON_FAIL_INVALID",
		1: "ON_FAIL_ERROR",
		2: "ON_FAIL_SKIP",
	}
	FindRunbookConfigurationSteps_Condition_OnFail_value = map[string]int32{
		"ON_FAIL_INVALID": 0,
		"ON_FAIL_ERROR":   1,
		"ON_FAIL_SKIP":    2,
	}
)

func (x FindRunbookConfigurationSteps_Condition_OnFail) Enum() *FindRunbookConfigurationSteps_Condition_OnFail {
	p := new(FindRunbookConfigurationSteps_Condition_OnFail)
	*p = x
	return p
}

func (x FindRunbookConfigurationSteps_Condition_OnFail) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindRunbookConfigurationSteps_Condition_OnFail) Descriptor() protoreflect.EnumDescriptor {
	return file_runbooks_proto_enumTypes[1].Descriptor()
}

func (FindRunbookConfigurationSteps_Condition_OnFail) Type() protoreflect.EnumType {
	return &file_runbooks_proto_enumTypes[1]
}

func (x FindRunbookConfigurationSteps_Condition_OnFail) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindRunbookConfigurationSteps_Condition_OnFail.Descriptor instead.
func (FindRunbookConfigurationSteps_Condition_OnFail) EnumDescriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5, 6, 0}
}

type DynamicValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msgpack       []byte                 `protobuf:"bytes,1,opt,name=msgpack,proto3" json:"msgpack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicValue) Reset() {
	*x = DynamicValue{}
	mi := &file_runbooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicValue) ProtoMessage() {}

func (x *DynamicValue) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicValue.ProtoReflect.Descriptor instead.
func (*DynamicValue) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{0}
}

func (x *DynamicValue) GetMsgpack() []byte {
	if x != nil {
		return x.Msgpack
	}
	return nil
}

type EvalScope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Variables available as var.<name>
	Variables *DynamicValue `protobuf:"bytes,1,opt,name=variables,proto3" json:"variables,omitempty"`
	// Search results available as list.<type>.<name>...
	List *DynamicValue `protobuf:"bytes,2,opt,name=list,proto3" json:"list,omitempty"`
	// Action results available as actions.<type>.<name>...
	Actions *DynamicValue `protobuf:"bytes,3,opt,name=actions,proto3" json:"actions,omitempty"`
	// Prior step outputs available as steps.<name>.<output>
	Steps *DynamicValue `protobuf:"bytes,4,opt,name=steps,proto3" json:"steps,omitempty"`
	// Step local values available as local.<name>
	Locals        *DynamicValue `protobuf:"bytes,5,opt,name=locals,proto3" json:"locals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalScope) Reset() {
	*x = EvalScope{}
	mi := &file_runbooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalScope) ProtoMessage() {}

func (x *EvalScope) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalScope.ProtoReflect.Descriptor instead.
func (*EvalScope) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{1}
}

func (x *EvalScope) GetVariables() *DynamicValue {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *EvalScope) GetList() *DynamicValue {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *EvalScope) GetActions() *DynamicValue {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *EvalScope) GetSteps() *DynamicValue {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *EvalScope) GetLocals() *DynamicValue {
	if x != nil {
		return x.Locals
	}
	return nil
}

type OpenRunbookConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRunbookConfiguration) Reset() {
	*x = OpenRunbookConfiguration{}
	mi := &file_runbooks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRunbookConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRunbookConfiguration) ProtoMessage() {}

func (x *OpenRunbookConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRunbookConfiguration.ProtoReflect.Descriptor instead.
func (*OpenRunbookConfiguration) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{2}
}

type CloseRunbookConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRunbookConfiguration) Reset() {
	*x = CloseRunbookConfiguration{}
	mi := &file_runbooks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRunbookConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRunbookConfiguration) ProtoMessage() {}

func (x *CloseRunbookConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRunbookConfiguration.ProtoReflect.Descriptor instead.
func (*CloseRunbookConfiguration) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{3}
}

type ValidateRunbookConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRunbookConfiguration) Reset() {
	*x = ValidateRunbookConfiguration{}
	mi := &file_runbooks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRunbookConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRunbookConfiguration) ProtoMessage() {}

func (x *ValidateRunbookConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRunbookConfiguration.ProtoReflect.Descriptor instead.
func (*ValidateRunbookConfiguration) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{4}
}

type FindRunbookConfigurationSteps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRunbookConfigurationSteps) Reset() {
	*x = FindRunbookConfigurationSteps{}
	mi := &file_runbooks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRunbookConfigurationSteps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRunbookConfigurationSteps) ProtoMessage() {}

func (x *FindRunbookConfigurationSteps) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRunbookConfigurationSteps.ProtoReflect.Descriptor instead.
func (*FindRunbookConfigurationSteps) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5}
}

type PlanRunbookStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRunbookStep) Reset() {
	*x = PlanRunbookStep{}
	mi := &file_runbooks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRunbookStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRunbookStep) ProtoMessage() {}

func (x *PlanRunbookStep) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRunbookStep.ProtoReflect.Descriptor instead.
func (*PlanRunbookStep) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{6}
}

type ExecuteRunbookStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRunbookStep) Reset() {
	*x = ExecuteRunbookStep{}
	mi := &file_runbooks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRunbookStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRunbookStep) ProtoMessage() {}

func (x *ExecuteRunbookStep) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRunbookStep.ProtoReflect.Descriptor instead.
func (*ExecuteRunbookStep) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{7}
}

type GetRunnableRunbookSteps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnableRunbookSteps) Reset() {
	*x = GetRunnableRunbookSteps{}
	mi := &file_runbooks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnableRunbookSteps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnableRunbookSteps) ProtoMessage() {}

func (x *GetRunnableRunbookSteps) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnableRunbookSteps.ProtoReflect.Descriptor instead.
func (*GetRunnableRunbookSteps) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{8}
}

type OpenRunbookConfiguration_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRunbookConfiguration_Request) Reset() {
	*x = OpenRunbookConfiguration_Request{}
	mi := &file_runbooks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRunbookConfiguration_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRunbookConfiguration_Request) ProtoMessage() {}

func (x *OpenRunbookConfiguration_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRunbookConfiguration_Request.ProtoReflect.Descriptor instead.
func (*OpenRunbookConfiguration_Request) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{2, 0}
}

func (x *OpenRunbookConfiguration_Request) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type OpenRunbookConfiguration_Response struct {
	state               protoimpl.MessageState   `protogen:"open.v1"`
	RunbookConfigHandle int64                    `protobuf:"varint,1,opt,name=runbook_config_handle,json=runbookConfigHandle,proto3" json:"runbook_config_handle,omitempty"`
	Diagnostics         []*terraform1.Diagnostic `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpenRunbookConfiguration_Response) Reset() {
	*x = OpenRunbookConfiguration_Response{}
	mi := &file_runbooks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRunbookConfiguration_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRunbookConfiguration_Response) ProtoMessage() {}

func (x *OpenRunbookConfiguration_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRunbookConfiguration_Response.ProtoReflect.Descriptor instead.
func (*OpenRunbookConfiguration_Response) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{2, 1}
}

func (x *OpenRunbookConfiguration_Response) GetRunbookConfigHandle() int64 {
	if x != nil {
		return x.RunbookConfigHandle
	}
	return 0
}

func (x *OpenRunbookConfiguration_Response) GetDiagnostics() []*terraform1.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type CloseRunbookConfiguration_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunbookConfigHandle int64                  `protobuf:"varint,1,opt,name=runbook_config_handle,json=runbookConfigHandle,proto3" json:"runbook_config_handle,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CloseRunbookConfiguration_Request) Reset() {
	*x = CloseRunbookConfiguration_Request{}
	mi := &file_runbooks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRunbookConfiguration_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRunbookConfiguration_Request) ProtoMessage() {}

func (x *CloseRunbookConfiguration_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRunbookConfiguration_Request.ProtoReflect.Descriptor instead.
func (*CloseRunbookConfiguration_Request) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CloseRunbookConfiguration_Request) GetRunbookConfigHandle() int64 {
	if x != nil {
		return x.RunbookConfigHandle
	}
	return 0
}

type CloseRunbookConfiguration_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRunbookConfiguration_Response) Reset() {
	*x = CloseRunbookConfiguration_Response{}
	mi := &file_runbooks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRunbookConfiguration_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRunbookConfiguration_Response) ProtoMessage() {}

func (x *CloseRunbookConfiguration_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRunbookConfiguration_Response.ProtoReflect.Descriptor instead.
func (*CloseRunbookConfiguration_Response) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{3, 1}
}

type ValidateRunbookConfiguration_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunbookConfigHandle int64                  `protobuf:"varint,1,opt,name=runbook_config_handle,json=runbookConfigHandle,proto3" json:"runbook_config_handle,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ValidateRunbookConfiguration_Request) Reset() {
	*x = ValidateRunbookConfiguration_Request{}
	mi := &file_runbooks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRunbookConfiguration_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRunbookConfiguration_Request) ProtoMessage() {}

func (x *ValidateRunbookConfiguration_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRunbookConfiguration_Request.ProtoReflect.Descriptor instead.
func (*ValidateRunbookConfiguration_Request) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ValidateRunbookConfiguration_Request) GetRunbookConfigHandle() int64 {
	if x != nil {
		return x.RunbookConfigHandle
	}
	return 0
}

type ValidateRunbookConfiguration_Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Diagnostics   []*terraform1.Diagnostic `protobuf:"bytes,1,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRunbookConfiguration_Response) Reset() {
	*x = ValidateRunbookConfiguration_Response{}
	mi := &file_runbooks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRunbookConfiguration_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRunbookConfiguration_Response) ProtoMessage() {}

func (x *ValidateRunbookConfiguration_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRunbookConfiguration_Response.ProtoReflect.Descriptor instead.
func (*ValidateRunbookConfiguration_Response) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ValidateRunbookConfiguration_Response) GetDiagnostics() []*terraform1.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type FindRunbookConfigurationSteps_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunbookConfigHandle int64                  `protobuf:"varint,1,opt,name=runbook_config_handle,json=runbookConfigHandle,proto3" json:"runbook_config_handle,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FindRunbookConfigurationSteps_Request) Reset() {
	*x = FindRunbookConfigurationSteps_Request{}
	mi := &file_runbooks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRunbookConfigurationSteps_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRunbookConfigurationSteps_Request) ProtoMessage() {}

func (x *FindRunbookConfigurationSteps_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRunbookConfigurationSteps_Request.ProtoReflect.Descriptor instead.
func (*FindRunbookConfigurationSteps_Request) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5, 0}
}

func (x *FindRunbookConfigurationSteps_Request) GetRunbookConfigHandle() int64 {
	if x != nil {
		return x.RunbookConfigHandle
	}
	return 0
}

type FindRunbookConfigurationSteps_Response struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Config        *FindRunbookConfigurationSteps_RunbookConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRunbookConfigurationSteps_Response) Reset() {
	*x = FindRunbookConfigurationSteps_Response{}
	mi := &file_runbooks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRunbookConfigurationSteps_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRunbookConfigurationSteps_Response) ProtoMessage() {}

func (x *FindRunbookConfigurationSteps_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRunbookConfigurationSteps_Response.ProtoReflect.Descriptor instead.
func (*FindRunbookConfigurationSteps_Response) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5, 1}
}

func (x *FindRunbookConfigurationSteps_Response) GetConfig() *FindRunbookConfigurationSteps_RunbookConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type FindRunbookConfigurationSteps_RunbookConfig struct {
	state            protoimpl.MessageState                          `protogen:"open.v1"`
	SourceAddr       string                                          `protobuf:"bytes,1,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	TerraformVersion string                                          `protobuf:"bytes,2,opt,name=terraform_version,json=terraformVersion,proto3" json:"terraform_version,omitempty"`
	Providers        []*FindRunbookConfigurationSteps_ProviderConfig `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	Steps            map[string]*FindRunbookConfigurationSteps_Step  `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Variables        []*FindRunbookConfigurationSteps_Variable       `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindRunbookConfigurationSteps_RunbookConfig) Reset() {
	*x = FindRunbookConfigurationSteps_RunbookConfig{}
	mi := &file_runbooks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRunbookConfigurationSteps_RunbookConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRunbookConfigurationSteps_RunbookConfig) ProtoMessage() {}

func (x *FindRunbookConfigurationSteps_RunbookConfig) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRunbookConfigurationSteps_RunbookConfig.ProtoReflect.Descriptor instead.
func (*FindRunbookConfigurationSteps_RunbookConfig) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5, 2}
}

func (x *FindRunbookConfigurationSteps_RunbookConfig) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *FindRunbookConfigurationSteps_RunbookConfig) GetTerraformVersion() string {
	if x != nil {
		return x.TerraformVersion
	}
	return ""
}

func (x *FindRunbookConfigurationSteps_RunbookConfig) GetProviders() []*FindRunbookConfigurationSteps_ProviderConfig {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *FindRunbookConfigurationSteps_RunbookConfig) GetSteps() map[string]*FindRunbookConfigurationSteps_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *FindRunbookConfigurationSteps_RunbookConfig) GetVariables() []*FindRunbookConfigurationSteps_Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type FindRunbookConfigurationSteps_ProviderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRunbookConfigurationSteps_ProviderConfig) Reset() {
	*x = FindRunbookConfigurationSteps_ProviderConfig{}
	mi := &file_runbooks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRunbookConfigurationSteps_ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRunbookConfigurationSteps_ProviderConfig) ProtoMessage() {}

func (x *FindRunbookConfigurationSteps_ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRunbookConfigurationSteps_ProviderConfig.ProtoReflect.Descriptor instead.
func (*FindRunbookConfigurationSteps_ProviderConfig) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5, 3}
}

func (x *FindRunbookConfigurationSteps_ProviderConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type FindRunbookConfigurationSteps_Step struct {
	state          protoimpl.MessageState                     `protogen:"open.v1"`
	HasConfig      bool                                       `protobuf:"varint,1,opt,name=has_config,json=hasConfig,proto3" json:"has_config,omitempty"`
	ActionCount    int64                                      `protobuf:"varint,2,opt,name=action_count,json=actionCount,proto3" json:"action_count,omitempty"`
	ListCount      int64                                      `protobuf:"varint,3,opt,name=list_count,json=listCount,proto3" json:"list_count,omitempty"`
	ExecuteCount   int64                                      `protobuf:"varint,4,opt,name=execute_count,json=executeCount,proto3" json:"execute_count,omitempty"`
	Preconditions  []*FindRunbookConfigurationSteps_Condition `protobuf:"bytes,5,rep,name=preconditions,proto3" json:"preconditions,omitempty"`
	Postconditions []*FindRunbookConfigurationSteps_Condition `protobuf:"bytes,6,rep,name=postconditions,proto3" json:"postconditions,omitempty"`
	Locals         []string                                   `protobuf:"bytes,7,rep,name=locals,proto3" json:"locals,omitempty"`
	Outputs        []string                                   `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindRunbookConfigurationSteps_Step) Reset() {
	*x = FindRunbookConfigurationSteps_Step{}
	mi := &file_runbooks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRunbookConfigurationSteps_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRunbookConfigurationSteps_Step) ProtoMessage() {}

func (x *FindRunbookConfigurationSteps_Step) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRunbookConfigurationSteps_Step.ProtoReflect.Descriptor instead.
func (*FindRunbookConfigurationSteps_Step) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5, 4}
}

func (x *FindRunbookConfigurationSteps_Step) GetHasConfig() bool {
	if x != nil {
		return x.HasConfig
	}
	return false
}

func (x *FindRunbookConfigurationSteps_Step) GetActionCount() int64 {
	if x != nil {
		return x.ActionCount
	}
	return 0
}

func (x *FindRunbookConfigurationSteps_Step) GetListCount() int64 {
	if x != nil {
		return x.ListCount
	}
	return 0
}

func (x *FindRunbookConfigurationSteps_Step) GetExecuteCount() int64 {
	if x != nil {
		return x.ExecuteCount
	}
	return 0
}

func (x *FindRunbookConfigurationSteps_Step) GetPreconditions() []*FindRunbookConfigurationSteps_Condition {
	if x != nil {
		return x.Preconditions
	}
	return nil
}

func (x *FindRunbookConfigurationSteps_Step) GetPostconditions() []*FindRunbookConfigurationSteps_Condition {
	if x != nil {
		return x.Postconditions
	}
	return nil
}

func (x *FindRunbookConfigurationSteps_Step) GetLocals() []string {
	if x != nil {
		return x.Locals
	}
	return nil
}

func (x *FindRunbookConfigurationSteps_Step) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type FindRunbookConfigurationSteps_Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HasDefault    bool                   `protobuf:"varint,2,opt,name=has_default,json=hasDefault,proto3" json:"has_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRunbookConfigurationSteps_Variable) Reset() {
	*x = FindRunbookConfigurationSteps_Variable{}
	mi := &file_runbooks_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRunbookConfigurationSteps_Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRunbookConfigurationSteps_Variable) ProtoMessage() {}

func (x *FindRunbookConfigurationSteps_Variable) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRunbookConfigurationSteps_Variable.ProtoReflect.Descriptor instead.
func (*FindRunbookConfigurationSteps_Variable) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5, 5}
}

func (x *FindRunbookConfigurationSteps_Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindRunbookConfigurationSteps_Variable) GetHasDefault() bool {
	if x != nil {
		return x.HasDefault
	}
	return false
}

type FindRunbookConfigurationSteps_Condition struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	OnFail        FindRunbookConfigurationSteps_Condition_OnFail `protobuf:"varint,1,opt,name=on_fail,json=onFail,proto3,enum=terraform1.runbooks.FindRunbookConfigurationSteps_Condition_OnFail" json:"on_fail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRunbookConfigurationSteps_Condition) Reset() {
	*x = FindRunbookConfigurationSteps_Condition{}
	mi := &file_runbooks_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRunbookConfigurationSteps_Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRunbookConfigurationSteps_Condition) ProtoMessage() {}

func (x *FindRunbookConfigurationSteps_Condition) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRunbookConfigurationSteps_Condition.ProtoReflect.Descriptor instead.
func (*FindRunbookConfigurationSteps_Condition) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{5, 6}
}

func (x *FindRunbookConfigurationSteps_Condition) GetOnFail() FindRunbookConfigurationSteps_Condition_OnFail {
	if x != nil {
		return x.OnFail
	}
	return FindRunbookConfigurationSteps_Condition_ON_FAIL_INVALID
}

type PlanRunbookStep_PlannedAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	ActionName    string                 `protobuf:"bytes,3,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRunbookStep_PlannedAction) Reset() {
	*x = PlanRunbookStep_PlannedAction{}
	mi := &file_runbooks_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRunbookStep_PlannedAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRunbookStep_PlannedAction) ProtoMessage() {}

func (x *PlanRunbookStep_PlannedAction) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRunbookStep_PlannedAction.ProtoReflect.Descriptor instead.
func (*PlanRunbookStep_PlannedAction) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{6, 0}
}

func (x *PlanRunbookStep_PlannedAction) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PlanRunbookStep_PlannedAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *PlanRunbookStep_PlannedAction) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

type PlanRunbookStep_LoweredFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanRunbookStep_LoweredFile) Reset() {
	*x = PlanRunbookStep_LoweredFile{}
	mi := &file_runbooks_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRunbookStep_LoweredFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRunbookStep_LoweredFile) ProtoMessage() {}

func (x *PlanRunbookStep_LoweredFile) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRunbookStep_LoweredFile.ProtoReflect.Descriptor instead.
func (*PlanRunbookStep_LoweredFile) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{6, 1}
}

func (x *PlanRunbookStep_LoweredFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PlanRunbookStep_LoweredFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PlanRunbookStep_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunbookConfigHandle int64                  `protobuf:"varint,1,opt,name=runbook_config_handle,json=runbookConfigHandle,proto3" json:"runbook_config_handle,omitempty"`
	StepName            string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Scope               *EvalScope             `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlanRunbookStep_Request) Reset() {
	*x = PlanRunbookStep_Request{}
	mi := &file_runbooks_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRunbookStep_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRunbookStep_Request) ProtoMessage() {}

func (x *PlanRunbookStep_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRunbookStep_Request.ProtoReflect.Descriptor instead.
func (*PlanRunbookStep_Request) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{6, 2}
}

func (x *PlanRunbookStep_Request) GetRunbookConfigHandle() int64 {
	if x != nil {
		return x.RunbookConfigHandle
	}
	return 0
}

func (x *PlanRunbookStep_Request) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *PlanRunbookStep_Request) GetScope() *EvalScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type PlanRunbookStep_Response struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	Status         StepStatus                       `protobuf:"varint,1,opt,name=status,proto3,enum=terraform1.runbooks.StepStatus" json:"status,omitempty"`
	Detail         string                           `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Diagnostics    []*terraform1.Diagnostic         `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	PlannedActions []*PlanRunbookStep_PlannedAction `protobuf:"bytes,4,rep,name=planned_actions,json=plannedActions,proto3" json:"planned_actions,omitempty"`
	LoweredFiles   []*PlanRunbookStep_LoweredFile   `protobuf:"bytes,5,rep,name=lowered_files,json=loweredFiles,proto3" json:"lowered_files,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanRunbookStep_Response) Reset() {
	*x = PlanRunbookStep_Response{}
	mi := &file_runbooks_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanRunbookStep_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanRunbookStep_Response) ProtoMessage() {}

func (x *PlanRunbookStep_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanRunbookStep_Response.ProtoReflect.Descriptor instead.
func (*PlanRunbookStep_Response) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{6, 3}
}

func (x *PlanRunbookStep_Response) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_INVALID
}

func (x *PlanRunbookStep_Response) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PlanRunbookStep_Response) GetDiagnostics() []*terraform1.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *PlanRunbookStep_Response) GetPlannedActions() []*PlanRunbookStep_PlannedAction {
	if x != nil {
		return x.PlannedActions
	}
	return nil
}

func (x *PlanRunbookStep_Response) GetLoweredFiles() []*PlanRunbookStep_LoweredFile {
	if x != nil {
		return x.LoweredFiles
	}
	return nil
}

type ExecuteRunbookStep_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunbookConfigHandle int64                  `protobuf:"varint,1,opt,name=runbook_config_handle,json=runbookConfigHandle,proto3" json:"runbook_config_handle,omitempty"`
	StepName            string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	PreExecuteScope     *EvalScope             `protobuf:"bytes,3,opt,name=pre_execute_scope,json=preExecuteScope,proto3" json:"pre_execute_scope,omitempty"`
	PostExecuteScope    *EvalScope             `protobuf:"bytes,4,opt,name=post_execute_scope,json=postExecuteScope,proto3" json:"post_execute_scope,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecuteRunbookStep_Request) Reset() {
	*x = ExecuteRunbookStep_Request{}
	mi := &file_runbooks_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRunbookStep_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRunbookStep_Request) ProtoMessage() {}

func (x *ExecuteRunbookStep_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRunbookStep_Request.ProtoReflect.Descriptor instead.
func (*ExecuteRunbookStep_Request) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ExecuteRunbookStep_Request) GetRunbookConfigHandle() int64 {
	if x != nil {
		return x.RunbookConfigHandle
	}
	return 0
}

func (x *ExecuteRunbookStep_Request) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ExecuteRunbookStep_Request) GetPreExecuteScope() *EvalScope {
	if x != nil {
		return x.PreExecuteScope
	}
	return nil
}

func (x *ExecuteRunbookStep_Request) GetPostExecuteScope() *EvalScope {
	if x != nil {
		return x.PostExecuteScope
	}
	return nil
}

type ExecuteRunbookStep_Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        StepStatus               `protobuf:"varint,1,opt,name=status,proto3,enum=terraform1.runbooks.StepStatus" json:"status,omitempty"`
	Detail        string                   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Diagnostics   []*terraform1.Diagnostic `protobuf:"bytes,3,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRunbookStep_Response) Reset() {
	*x = ExecuteRunbookStep_Response{}
	mi := &file_runbooks_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRunbookStep_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRunbookStep_Response) ProtoMessage() {}

func (x *ExecuteRunbookStep_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRunbookStep_Response.ProtoReflect.Descriptor instead.
func (*ExecuteRunbookStep_Response) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{7, 1}
}

func (x *ExecuteRunbookStep_Response) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_INVALID
}

func (x *ExecuteRunbookStep_Response) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ExecuteRunbookStep_Response) GetDiagnostics() []*terraform1.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type GetRunnableRunbookSteps_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunbookConfigHandle int64                  `protobuf:"varint,1,opt,name=runbook_config_handle,json=runbookConfigHandle,proto3" json:"runbook_config_handle,omitempty"`
	CompletedSteps      []string               `protobuf:"bytes,2,rep,name=completed_steps,json=completedSteps,proto3" json:"completed_steps,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRunnableRunbookSteps_Request) Reset() {
	*x = GetRunnableRunbookSteps_Request{}
	mi := &file_runbooks_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnableRunbookSteps_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnableRunbookSteps_Request) ProtoMessage() {}

func (x *GetRunnableRunbookSteps_Request) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnableRunbookSteps_Request.ProtoReflect.Descriptor instead.
func (*GetRunnableRunbookSteps_Request) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetRunnableRunbookSteps_Request) GetRunbookConfigHandle() int64 {
	if x != nil {
		return x.RunbookConfigHandle
	}
	return 0
}

func (x *GetRunnableRunbookSteps_Request) GetCompletedSteps() []string {
	if x != nil {
		return x.CompletedSteps
	}
	return nil
}

type GetRunnableRunbookSteps_Response struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	StepNames     []string                 `protobuf:"bytes,1,rep,name=step_names,json=stepNames,proto3" json:"step_names,omitempty"`
	Diagnostics   []*terraform1.Diagnostic `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunnableRunbookSteps_Response) Reset() {
	*x = GetRunnableRunbookSteps_Response{}
	mi := &file_runbooks_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunnableRunbookSteps_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunnableRunbookSteps_Response) ProtoMessage() {}

func (x *GetRunnableRunbookSteps_Response) ProtoReflect() protoreflect.Message {
	mi := &file_runbooks_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunnableRunbookSteps_Response.ProtoReflect.Descriptor instead.
func (*GetRunnableRunbookSteps_Response) Descriptor() ([]byte, []int) {
	return file_runbooks_proto_rawDescGZIP(), []int{8, 1}
}

func (x *GetRunnableRunbookSteps_Response) GetStepNames() []string {
	if x != nil {
		return x.StepNames
	}
	return nil
}

func (x *GetRunnableRunbookSteps_Response) GetDiagnostics() []*terraform1.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

var File_runbooks_proto protoreflect.FileDescriptor

const file_runbooks_proto_rawDesc = "" +
	"\n" +
	"\x0erunbooks.proto\x12\x13terraform1.runbooks\x1a\x10terraform1.proto\"(\n" +
	"\fDynamicValue\x12\x18\n" +
	"\amsgpack\x18\x01 \x01(\fR\amsgpack\"\xb4\x02\n" +
	"\tEvalScope\x12?\n" +
	"\tvariables\x18\x01 \x01(\v2!.terraform1.runbooks.DynamicValueR\tvariables\x125\n" +
	"\x04list\x18\x02 \x01(\v2!.terraform1.runbooks.DynamicValueR\x04list\x12;\n" +
	"\aactions\x18\x03 \x01(\v2!.terraform1.runbooks.DynamicValueR\aactions\x127\n" +
	"\x05steps\x18\x04 \x01(\v2!.terraform1.runbooks.DynamicValueR\x05steps\x129\n" +
	"\x06locals\x18\x05 \x01(\v2!.terraform1.runbooks.DynamicValueR\x06locals\"\xc0\x01\n" +
	"\x18OpenRunbookConfiguration\x1a*\n" +
	"\aRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x1ax\n" +
	"\bResponse\x122\n" +
	"\x15runbook_config_handle\x18\x01 \x01(\x03R\x13runbookConfigHandle\x128\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x16.terraform1.DiagnosticR\vdiagnostics\"f\n" +
	"\x19CloseRunbookConfiguration\x1a=\n" +
	"\aRequest\x122\n" +
	"\x15runbook_config_handle\x18\x01 \x01(\x03R\x13runbookConfigHandle\x1a\n" +
	"\n" +
	"\bResponse\"\xa3\x01\n" +
	"\x1cValidateRunbookConfiguration\x1a=\n" +
	"\aRequest\x122\n" +
	"\x15runbook_config_handle\x18\x01 \x01(\x03R\x13runbookConfigHandle\x1aD\n" +
	"\bResponse\x128\n" +
	"\vdiagnostics\x18\x01 \x03(\v2\x16.terraform1.DiagnosticR\vdiagnostics\"\xd8\n" +
	"\n" +
	"\x1dFindRunbookConfigurationSteps\x1a=\n" +
	"\aRequest\x122\n" +
	"\x15runbook_config_handle\x18\x01 \x01(\x03R\x13runbookConfigHandle\x1ad\n" +
	"\bResponse\x12X\n" +
	"\x06config\x18\x01 \x01(\v2@.terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfigR\x06config\x1a\xef\x03\n" +
	"\rRunbookConfig\x12\x1f\n" +
	"\vsource_addr\x18\x01 \x01(\tR\n" +
	"sourceAddr\x12+\n" +
	"\x11terraform_version\x18\x02 \x01(\tR\x10terraformVersion\x12_\n" +
	"\tproviders\x18\x03 \x03(\v2A.terraform1.runbooks.FindRunbookConfigurationSteps.ProviderConfigR\tproviders\x12a\n" +
	"\x05steps\x18\x04 \x03(\v2K.terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig.StepsEntryR\x05steps\x12Y\n" +
	"\tvariables\x18\x05 \x03(\v2;.terraform1.runbooks.FindRunbookConfigurationSteps.VariableR\tvariables\x1aq\n" +
	"\n" +
	"StepsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12M\n" +
	"\x05value\x18\x02 \x01(\v27.terraform1.runbooks.FindRunbookConfigurationSteps.StepR\x05value:\x028\x01\x1a$\n" +
	"\x0eProviderConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x1a\x88\x03\n" +
	"\x04Step\x12\x1d\n" +
	"\n" +
	"has_config\x18\x01 \x01(\bR\thasConfig\x12!\n" +
	"\faction_count\x18\x02 \x01(\x03R\vactionCount\x12\x1d\n" +
	"\n" +
	"list_count\x18\x03 \x01(\x03R\tlistCount\x12#\n" +
	"\rexecute_count\x18\x04 \x01(\x03R\fexecuteCount\x12b\n" +
	"\rpreconditions\x18\x05 \x03(\v2<.terraform1.runbooks.FindRunbookConfigurationSteps.ConditionR\rpreconditions\x12d\n" +
	"\x0epostconditions\x18\x06 \x03(\v2<.terraform1.runbooks.FindRunbookConfigurationSteps.ConditionR\x0epostconditions\x12\x16\n" +
	"\x06locals\x18\a \x03(\tR\x06locals\x12\x18\n" +
	"\aoutputs\x18\b \x03(\tR\aoutputs\x1a?\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vhas_default\x18\x02 \x01(\bR\n" +
	"hasDefault\x1a\xad\x01\n" +
	"\tCondition\x12\\\n" +
	"\aon_fail\x18\x01 \x01(\x0e2C.terraform1.runbooks.FindRunbookConfigurationSteps.Condition.OnFailR\x06onFail\"B\n" +
	"\x06OnFail\x12\x13\n" +
	"\x0fON_FAIL_INVALID\x10\x00\x12\x11\n" +
	"\rON_FAIL_ERROR\x10\x01\x12\x10\n" +
	"\fON_FAIL_SKIP\x10\x02\"\x9a\x05\n" +
	"\x0fPlanRunbookStep\x1ak\n" +
	"\rPlannedAction\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x1f\n" +
	"\vaction_name\x18\x03 \x01(\tR\n" +
	"actionName\x1a;\n" +
	"\vLoweredFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x1a\x90\x01\n" +
	"\aRequest\x122\n" +
	"\x15runbook_config_handle\x18\x01 \x01(\x03R\x13runbookConfigHandle\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x124\n" +
	"\x05scope\x18\x03 \x01(\v2\x1e.terraform1.runbooks.EvalScopeR\x05scope\x1a\xc9\x02\n" +
	"\bResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.terraform1.runbooks.StepStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x128\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x16.terraform1.DiagnosticR\vdiagnostics\x12[\n" +
	"\x0fplanned_actions\x18\x04 \x03(\v22.terraform1.runbooks.PlanRunbookStep.PlannedActionR\x0eplannedActions\x12U\n" +
	"\rlowered_files\x18\x05 \x03(\v20.terraform1.runbooks.PlanRunbookStep.LoweredFileR\floweredFiles\"\xa3\x03\n" +
	"\x12ExecuteRunbookStep\x1a\xf4\x01\n" +
	"\aRequest\x122\n" +
	"\x15runbook_config_handle\x18\x01 \x01(\x03R\x13runbookConfigHandle\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12J\n" +
	"\x11pre_execute_scope\x18\x03 \x01(\v2\x1e.terraform1.runbooks.EvalScopeR\x0fpreExecuteScope\x12L\n" +
	"\x12post_execute_scope\x18\x04 \x01(\v2\x1e.terraform1.runbooks.EvalScopeR\x10postExecuteScope\x1a\x95\x01\n" +
	"\bResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.terraform1.runbooks.StepStatusR\x06status\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x128\n" +
	"\vdiagnostics\x18\x03 \x03(\v2\x16.terraform1.DiagnosticR\vdiagnostics\"\xe6\x01\n" +
	"\x17GetRunnableRunbookSteps\x1af\n" +
	"\aRequest\x122\n" +
	"\x15runbook_config_handle\x18\x01 \x01(\x03R\x13runbookConfigHandle\x12'\n" +
	"\x0fcompleted_steps\x18\x02 \x03(\tR\x0ecompletedSteps\x1ac\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"step_names\x18\x01 \x03(\tR\tstepNames\x128\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x16.terraform1.DiagnosticR\vdiagnostics*\x88\x01\n" +
	"\n" +
	"StepStatus\x12\x17\n" +
	"\x13STEP_STATUS_INVALID\x10\x00\x12\x15\n" +
	"\x11STEP_STATUS_READY\x10\x01\x12\x17\n" +
	"\x13STEP_STATUS_SKIPPED\x10\x02\x12\x16\n" +
	"\x12STEP_STATUS_FAILED\x10\x03\x12\x19\n" +
	"\x15STEP_STATUS_SUCCEEDED\x10\x042\xca\a\n" +
	"\bRunbooks\x12\x89\x01\n" +
	"\x18OpenRunbookConfiguration\x125.terraform1.runbooks.OpenRunbookConfiguration.Request\x1a6.terraform1.runbooks.OpenRunbookConfiguration.Response\x12\x8c\x01\n" +
	"\x19CloseRunbookConfiguration\x126.terraform1.runbooks.CloseRunbookConfiguration.Request\x1a7.terraform1.runbooks.CloseRunbookConfiguration.Response\x12\x95\x01\n" +
	"\x1cValidateRunbookConfiguration\x129.terraform1.runbooks.ValidateRunbookConfiguration.Request\x1a:.terraform1.runbooks.ValidateRunbookConfiguration.Response\x12\x98\x01\n" +
	"\x1dFindRunbookConfigurationSteps\x12:.terraform1.runbooks.FindRunbookConfigurationSteps.Request\x1a;.terraform1.runbooks.FindRunbookConfigurationSteps.Response\x12n\n" +
	"\x0fPlanRunbookStep\x12,.terraform1.runbooks.PlanRunbookStep.Request\x1a-.terraform1.runbooks.PlanRunbookStep.Response\x12w\n" +
	"\x12ExecuteRunbookStep\x12/.terraform1.runbooks.ExecuteRunbookStep.Request\x1a0.terraform1.runbooks.ExecuteRunbookStep.Response\x12\x86\x01\n" +
	"\x17GetRunnableRunbookSteps\x124.terraform1.runbooks.GetRunnableRunbookSteps.Request\x1a5.terraform1.runbooks.GetRunnableRunbookSteps.Responseb\x06proto3"

var (
	file_runbooks_proto_rawDescOnce sync.Once
	file_runbooks_proto_rawDescData []byte
)

func file_runbooks_proto_rawDescGZIP() []byte {
	file_runbooks_proto_rawDescOnce.Do(func() {
		file_runbooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runbooks_proto_rawDesc), len(file_runbooks_proto_rawDesc)))
	})
	return file_runbooks_proto_rawDescData
}

var file_runbooks_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_runbooks_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_runbooks_proto_goTypes = []any{
	(StepStatus)(0), // 0: terraform1.runbooks.StepStatus
	(FindRunbookConfigurationSteps_Condition_OnFail)(0), // 1: terraform1.runbooks.FindRunbookConfigurationSteps.Condition.OnFail
	(*DynamicValue)(nil),                                 // 2: terraform1.runbooks.DynamicValue
	(*EvalScope)(nil),                                    // 3: terraform1.runbooks.EvalScope
	(*OpenRunbookConfiguration)(nil),                     // 4: terraform1.runbooks.OpenRunbookConfiguration
	(*CloseRunbookConfiguration)(nil),                    // 5: terraform1.runbooks.CloseRunbookConfiguration
	(*ValidateRunbookConfiguration)(nil),                 // 6: terraform1.runbooks.ValidateRunbookConfiguration
	(*FindRunbookConfigurationSteps)(nil),                // 7: terraform1.runbooks.FindRunbookConfigurationSteps
	(*PlanRunbookStep)(nil),                              // 8: terraform1.runbooks.PlanRunbookStep
	(*ExecuteRunbookStep)(nil),                           // 9: terraform1.runbooks.ExecuteRunbookStep
	(*GetRunnableRunbookSteps)(nil),                      // 10: terraform1.runbooks.GetRunnableRunbookSteps
	(*OpenRunbookConfiguration_Request)(nil),             // 11: terraform1.runbooks.OpenRunbookConfiguration.Request
	(*OpenRunbookConfiguration_Response)(nil),            // 12: terraform1.runbooks.OpenRunbookConfiguration.Response
	(*CloseRunbookConfiguration_Request)(nil),            // 13: terraform1.runbooks.CloseRunbookConfiguration.Request
	(*CloseRunbookConfiguration_Response)(nil),           // 14: terraform1.runbooks.CloseRunbookConfiguration.Response
	(*ValidateRunbookConfiguration_Request)(nil),         // 15: terraform1.runbooks.ValidateRunbookConfiguration.Request
	(*ValidateRunbookConfiguration_Response)(nil),        // 16: terraform1.runbooks.ValidateRunbookConfiguration.Response
	(*FindRunbookConfigurationSteps_Request)(nil),        // 17: terraform1.runbooks.FindRunbookConfigurationSteps.Request
	(*FindRunbookConfigurationSteps_Response)(nil),       // 18: terraform1.runbooks.FindRunbookConfigurationSteps.Response
	(*FindRunbookConfigurationSteps_RunbookConfig)(nil),  // 19: terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig
	(*FindRunbookConfigurationSteps_ProviderConfig)(nil), // 20: terraform1.runbooks.FindRunbookConfigurationSteps.ProviderConfig
	(*FindRunbookConfigurationSteps_Step)(nil),           // 21: terraform1.runbooks.FindRunbookConfigurationSteps.Step
	(*FindRunbookConfigurationSteps_Variable)(nil),       // 22: terraform1.runbooks.FindRunbookConfigurationSteps.Variable
	(*FindRunbookConfigurationSteps_Condition)(nil),      // 23: terraform1.runbooks.FindRunbookConfigurationSteps.Condition
	nil,                                      // 24: terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig.StepsEntry
	(*PlanRunbookStep_PlannedAction)(nil),    // 25: terraform1.runbooks.PlanRunbookStep.PlannedAction
	(*PlanRunbookStep_LoweredFile)(nil),      // 26: terraform1.runbooks.PlanRunbookStep.LoweredFile
	(*PlanRunbookStep_Request)(nil),          // 27: terraform1.runbooks.PlanRunbookStep.Request
	(*PlanRunbookStep_Response)(nil),         // 28: terraform1.runbooks.PlanRunbookStep.Response
	(*ExecuteRunbookStep_Request)(nil),       // 29: terraform1.runbooks.ExecuteRunbookStep.Request
	(*ExecuteRunbookStep_Response)(nil),      // 30: terraform1.runbooks.ExecuteRunbookStep.Response
	(*GetRunnableRunbookSteps_Request)(nil),  // 31: terraform1.runbooks.GetRunnableRunbookSteps.Request
	(*GetRunnableRunbookSteps_Response)(nil), // 32: terraform1.runbooks.GetRunnableRunbookSteps.Response
	(*terraform1.Diagnostic)(nil),            // 33: terraform1.Diagnostic
}
var file_runbooks_proto_depIdxs = []int32{
	2,  // 0: terraform1.runbooks.EvalScope.variables:type_name -> terraform1.runbooks.DynamicValue
	2,  // 1: terraform1.runbooks.EvalScope.list:type_name -> terraform1.runbooks.DynamicValue
	2,  // 2: terraform1.runbooks.EvalScope.actions:type_name -> terraform1.runbooks.DynamicValue
	2,  // 3: terraform1.runbooks.EvalScope.steps:type_name -> terraform1.runbooks.DynamicValue
	2,  // 4: terraform1.runbooks.EvalScope.locals:type_name -> terraform1.runbooks.DynamicValue
	33, // 5: terraform1.runbooks.OpenRunbookConfiguration.Response.diagnostics:type_name -> terraform1.Diagnostic
	33, // 6: terraform1.runbooks.ValidateRunbookConfiguration.Response.diagnostics:type_name -> terraform1.Diagnostic
	19, // 7: terraform1.runbooks.FindRunbookConfigurationSteps.Response.config:type_name -> terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig
	20, // 8: terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig.providers:type_name -> terraform1.runbooks.FindRunbookConfigurationSteps.ProviderConfig
	24, // 9: terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig.steps:type_name -> terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig.StepsEntry
	22, // 10: terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig.variables:type_name -> terraform1.runbooks.FindRunbookConfigurationSteps.Variable
	23, // 11: terraform1.runbooks.FindRunbookConfigurationSteps.Step.preconditions:type_name -> terraform1.runbooks.FindRunbookConfigurationSteps.Condition
	23, // 12: terraform1.runbooks.FindRunbookConfigurationSteps.Step.postconditions:type_name -> terraform1.runbooks.FindRunbookConfigurationSteps.Condition
	1,  // 13: terraform1.runbooks.FindRunbookConfigurationSteps.Condition.on_fail:type_name -> terraform1.runbooks.FindRunbookConfigurationSteps.Condition.OnFail
	21, // 14: terraform1.runbooks.FindRunbookConfigurationSteps.RunbookConfig.StepsEntry.value:type_name -> terraform1.runbooks.FindRunbookConfigurationSteps.Step
	3,  // 15: terraform1.runbooks.PlanRunbookStep.Request.scope:type_name -> terraform1.runbooks.EvalScope
	0,  // 16: terraform1.runbooks.PlanRunbookStep.Response.status:type_name -> terraform1.runbooks.StepStatus
	33, // 17: terraform1.runbooks.PlanRunbookStep.Response.diagnostics:type_name -> terraform1.Diagnostic
	25, // 18: terraform1.runbooks.PlanRunbookStep.Response.planned_actions:type_name -> terraform1.runbooks.PlanRunbookStep.PlannedAction
	26, // 19: terraform1.runbooks.PlanRunbookStep.Response.lowered_files:type_name -> terraform1.runbooks.PlanRunbookStep.LoweredFile
	3,  // 20: terraform1.runbooks.ExecuteRunbookStep.Request.pre_execute_scope:type_name -> terraform1.runbooks.EvalScope
	3,  // 21: terraform1.runbooks.ExecuteRunbookStep.Request.post_execute_scope:type_name -> terraform1.runbooks.EvalScope
	0,  // 22: terraform1.runbooks.ExecuteRunbookStep.Response.status:type_name -> terraform1.runbooks.StepStatus
	33, // 23: terraform1.runbooks.ExecuteRunbookStep.Response.diagnostics:type_name -> terraform1.Diagnostic
	33, // 24: terraform1.runbooks.GetRunnableRunbookSteps.Response.diagnostics:type_name -> terraform1.Diagnostic
	11, // 25: terraform1.runbooks.Runbooks.OpenRunbookConfiguration:input_type -> terraform1.runbooks.OpenRunbookConfiguration.Request
	13, // 26: terraform1.runbooks.Runbooks.CloseRunbookConfiguration:input_type -> terraform1.runbooks.CloseRunbookConfiguration.Request
	15, // 27: terraform1.runbooks.Runbooks.ValidateRunbookConfiguration:input_type -> terraform1.runbooks.ValidateRunbookConfiguration.Request
	17, // 28: terraform1.runbooks.Runbooks.FindRunbookConfigurationSteps:input_type -> terraform1.runbooks.FindRunbookConfigurationSteps.Request
	27, // 29: terraform1.runbooks.Runbooks.PlanRunbookStep:input_type -> terraform1.runbooks.PlanRunbookStep.Request
	29, // 30: terraform1.runbooks.Runbooks.ExecuteRunbookStep:input_type -> terraform1.runbooks.ExecuteRunbookStep.Request
	31, // 31: terraform1.runbooks.Runbooks.GetRunnableRunbookSteps:input_type -> terraform1.runbooks.GetRunnableRunbookSteps.Request
	12, // 32: terraform1.runbooks.Runbooks.OpenRunbookConfiguration:output_type -> terraform1.runbooks.OpenRunbookConfiguration.Response
	14, // 33: terraform1.runbooks.Runbooks.CloseRunbookConfiguration:output_type -> terraform1.runbooks.CloseRunbookConfiguration.Response
	16, // 34: terraform1.runbooks.Runbooks.ValidateRunbookConfiguration:output_type -> terraform1.runbooks.ValidateRunbookConfiguration.Response
	18, // 35: terraform1.runbooks.Runbooks.FindRunbookConfigurationSteps:output_type -> terraform1.runbooks.FindRunbookConfigurationSteps.Response
	28, // 36: terraform1.runbooks.Runbooks.PlanRunbookStep:output_type -> terraform1.runbooks.PlanRunbookStep.Response
	30, // 37: terraform1.runbooks.Runbooks.ExecuteRunbookStep:output_type -> terraform1.runbooks.ExecuteRunbookStep.Response
	32, // 38: terraform1.runbooks.Runbooks.GetRunnableRunbookSteps:output_type -> terraform1.runbooks.GetRunnableRunbookSteps.Response
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_runbooks_proto_init() }
func file_runbooks_proto_init() {
	if File_runbooks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runbooks_proto_rawDesc), len(file_runbooks_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runbooks_proto_goTypes,
		DependencyIndexes: file_runbooks_proto_depIdxs,
		EnumInfos:         file_runbooks_proto_enumTypes,
		MessageInfos:      file_runbooks_proto_msgTypes,
	}.Build()
	File_runbooks_proto = out.File
	file_runbooks_proto_goTypes = nil
	file_runbooks_proto_depIdxs = nil
}
