// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: runbooks.proto

package runbooks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runbooks_OpenRunbookConfiguration_FullMethodName      = "/terraform1.runbooks.Runbooks/OpenRunbookConfiguration"
	Runbooks_CloseRunbookConfiguration_FullMethodName     = "/terraform1.runbooks.Runbooks/CloseRunbookConfiguration"
	Runbooks_ValidateRunbookConfiguration_FullMethodName  = "/terraform1.runbooks.Runbooks/ValidateRunbookConfiguration"
	Runbooks_FindRunbookConfigurationSteps_FullMethodName = "/terraform1.runbooks.Runbooks/FindRunbookConfigurationSteps"
	Runbooks_PlanRunbookStep_FullMethodName               = "/terraform1.runbooks.Runbooks/PlanRunbookStep"
	Runbooks_ExecuteRunbookStep_FullMethodName            = "/terraform1.runbooks.Runbooks/ExecuteRunbookStep"
	Runbooks_GetRunnableRunbookSteps_FullMethodName       = "/terraform1.runbooks.Runbooks/GetRunnableRunbookSteps"
)

// RunbooksClient is the client API for Runbooks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunbooksClient interface {
	OpenRunbookConfiguration(ctx context.Context, in *OpenRunbookConfiguration_Request, opts ...grpc.CallOption) (*OpenRunbookConfiguration_Response, error)
	CloseRunbookConfiguration(ctx context.Context, in *CloseRunbookConfiguration_Request, opts ...grpc.CallOption) (*CloseRunbookConfiguration_Response, error)
	ValidateRunbookConfiguration(ctx context.Context, in *ValidateRunbookConfiguration_Request, opts ...grpc.CallOption) (*ValidateRunbookConfiguration_Response, error)
	FindRunbookConfigurationSteps(ctx context.Context, in *FindRunbookConfigurationSteps_Request, opts ...grpc.CallOption) (*FindRunbookConfigurationSteps_Response, error)
	PlanRunbookStep(ctx context.Context, in *PlanRunbookStep_Request, opts ...grpc.CallOption) (*PlanRunbookStep_Response, error)
	ExecuteRunbookStep(ctx context.Context, in *ExecuteRunbookStep_Request, opts ...grpc.CallOption) (*ExecuteRunbookStep_Response, error)
	GetRunnableRunbookSteps(ctx context.Context, in *GetRunnableRunbookSteps_Request, opts ...grpc.CallOption) (*GetRunnableRunbookSteps_Response, error)
}

type runbooksClient struct {
	cc grpc.ClientConnInterface
}

func NewRunbooksClient(cc grpc.ClientConnInterface) RunbooksClient {
	return &runbooksClient{cc}
}

func (c *runbooksClient) OpenRunbookConfiguration(ctx context.Context, in *OpenRunbookConfiguration_Request, opts ...grpc.CallOption) (*OpenRunbookConfiguration_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenRunbookConfiguration_Response)
	err := c.cc.Invoke(ctx, Runbooks_OpenRunbookConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runbooksClient) CloseRunbookConfiguration(ctx context.Context, in *CloseRunbookConfiguration_Request, opts ...grpc.CallOption) (*CloseRunbookConfiguration_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseRunbookConfiguration_Response)
	err := c.cc.Invoke(ctx, Runbooks_CloseRunbookConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runbooksClient) ValidateRunbookConfiguration(ctx context.Context, in *ValidateRunbookConfiguration_Request, opts ...grpc.CallOption) (*ValidateRunbookConfiguration_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRunbookConfiguration_Response)
	err := c.cc.Invoke(ctx, Runbooks_ValidateRunbookConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runbooksClient) FindRunbookConfigurationSteps(ctx context.Context, in *FindRunbookConfigurationSteps_Request, opts ...grpc.CallOption) (*FindRunbookConfigurationSteps_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRunbookConfigurationSteps_Response)
	err := c.cc.Invoke(ctx, Runbooks_FindRunbookConfigurationSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runbooksClient) PlanRunbookStep(ctx context.Context, in *PlanRunbookStep_Request, opts ...grpc.CallOption) (*PlanRunbookStep_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanRunbookStep_Response)
	err := c.cc.Invoke(ctx, Runbooks_PlanRunbookStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runbooksClient) ExecuteRunbookStep(ctx context.Context, in *ExecuteRunbookStep_Request, opts ...grpc.CallOption) (*ExecuteRunbookStep_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteRunbookStep_Response)
	err := c.cc.Invoke(ctx, Runbooks_ExecuteRunbookStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runbooksClient) GetRunnableRunbookSteps(ctx context.Context, in *GetRunnableRunbookSteps_Request, opts ...grpc.CallOption) (*GetRunnableRunbookSteps_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunnableRunbookSteps_Response)
	err := c.cc.Invoke(ctx, Runbooks_GetRunnableRunbookSteps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunbooksServer is the server API for Runbooks service.
// All implementations must embed UnimplementedRunbooksServer
// for forward compatibility.
type RunbooksServer interface {
	OpenRunbookConfiguration(context.Context, *OpenRunbookConfiguration_Request) (*OpenRunbookConfiguration_Response, error)
	CloseRunbookConfiguration(context.Context, *CloseRunbookConfiguration_Request) (*CloseRunbookConfiguration_Response, error)
	ValidateRunbookConfiguration(context.Context, *ValidateRunbookConfiguration_Request) (*ValidateRunbookConfiguration_Response, error)
	FindRunbookConfigurationSteps(context.Context, *FindRunbookConfigurationSteps_Request) (*FindRunbookConfigurationSteps_Response, error)
	PlanRunbookStep(context.Context, *PlanRunbookStep_Request) (*PlanRunbookStep_Response, error)
	ExecuteRunbookStep(context.Context, *ExecuteRunbookStep_Request) (*ExecuteRunbookStep_Response, error)
	GetRunnableRunbookSteps(context.Context, *GetRunnableRunbookSteps_Request) (*GetRunnableRunbookSteps_Response, error)
	mustEmbedUnimplementedRunbooksServer()
}

// UnimplementedRunbooksServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunbooksServer struct{}

func (UnimplementedRunbooksServer) OpenRunbookConfiguration(context.Context, *OpenRunbookConfiguration_Request) (*OpenRunbookConfiguration_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenRunbookConfiguration not implemented")
}
func (UnimplementedRunbooksServer) CloseRunbookConfiguration(context.Context, *CloseRunbookConfiguration_Request) (*CloseRunbookConfiguration_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseRunbookConfiguration not implemented")
}
func (UnimplementedRunbooksServer) ValidateRunbookConfiguration(context.Context, *ValidateRunbookConfiguration_Request) (*ValidateRunbookConfiguration_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRunbookConfiguration not implemented")
}
func (UnimplementedRunbooksServer) FindRunbookConfigurationSteps(context.Context, *FindRunbookConfigurationSteps_Request) (*FindRunbookConfigurationSteps_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindRunbookConfigurationSteps not implemented")
}
func (UnimplementedRunbooksServer) PlanRunbookStep(context.Context, *PlanRunbookStep_Request) (*PlanRunbookStep_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanRunbookStep not implemented")
}
func (UnimplementedRunbooksServer) ExecuteRunbookStep(context.Context, *ExecuteRunbookStep_Request) (*ExecuteRunbookStep_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteRunbookStep not implemented")
}
func (UnimplementedRunbooksServer) GetRunnableRunbookSteps(context.Context, *GetRunnableRunbookSteps_Request) (*GetRunnableRunbookSteps_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunnableRunbookSteps not implemented")
}
func (UnimplementedRunbooksServer) mustEmbedUnimplementedRunbooksServer() {}
func (UnimplementedRunbooksServer) testEmbeddedByValue()                  {}

// UnsafeRunbooksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunbooksServer will
// result in compilation errors.
type UnsafeRunbooksServer interface {
	mustEmbedUnimplementedRunbooksServer()
}

func RegisterRunbooksServer(s grpc.ServiceRegistrar, srv RunbooksServer) {
	// If the following call pancis, it indicates UnimplementedRunbooksServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runbooks_ServiceDesc, srv)
}

func _Runbooks_OpenRunbookConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRunbookConfiguration_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbooksServer).OpenRunbookConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runbooks_OpenRunbookConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbooksServer).OpenRunbookConfiguration(ctx, req.(*OpenRunbookConfiguration_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runbooks_CloseRunbookConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRunbookConfiguration_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbooksServer).CloseRunbookConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runbooks_CloseRunbookConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbooksServer).CloseRunbookConfiguration(ctx, req.(*CloseRunbookConfiguration_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runbooks_ValidateRunbookConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRunbookConfiguration_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbooksServer).ValidateRunbookConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runbooks_ValidateRunbookConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbooksServer).ValidateRunbookConfiguration(ctx, req.(*ValidateRunbookConfiguration_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runbooks_FindRunbookConfigurationSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRunbookConfigurationSteps_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbooksServer).FindRunbookConfigurationSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runbooks_FindRunbookConfigurationSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbooksServer).FindRunbookConfigurationSteps(ctx, req.(*FindRunbookConfigurationSteps_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runbooks_PlanRunbookStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRunbookStep_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbooksServer).PlanRunbookStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runbooks_PlanRunbookStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbooksServer).PlanRunbookStep(ctx, req.(*PlanRunbookStep_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runbooks_ExecuteRunbookStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRunbookStep_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbooksServer).ExecuteRunbookStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runbooks_ExecuteRunbookStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbooksServer).ExecuteRunbookStep(ctx, req.(*ExecuteRunbookStep_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runbooks_GetRunnableRunbookSteps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnableRunbookSteps_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbooksServer).GetRunnableRunbookSteps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runbooks_GetRunnableRunbookSteps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbooksServer).GetRunnableRunbookSteps(ctx, req.(*GetRunnableRunbookSteps_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Runbooks_ServiceDesc is the grpc.ServiceDesc for Runbooks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runbooks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "terraform1.runbooks.Runbooks",
	HandlerType: (*RunbooksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenRunbookConfiguration",
			Handler:    _Runbooks_OpenRunbookConfiguration_Handler,
		},
		{
			MethodName: "CloseRunbookConfiguration",
			Handler:    _Runbooks_CloseRunbookConfiguration_Handler,
		},
		{
			MethodName: "ValidateRunbookConfiguration",
			Handler:    _Runbooks_ValidateRunbookConfiguration_Handler,
		},
		{
			MethodName: "FindRunbookConfigurationSteps",
			Handler:    _Runbooks_FindRunbookConfigurationSteps_Handler,
		},
		{
			MethodName: "PlanRunbookStep",
			Handler:    _Runbooks_PlanRunbookStep_Handler,
		},
		{
			MethodName: "ExecuteRunbookStep",
			Handler:    _Runbooks_ExecuteRunbookStep_Handler,
		},
		{
			MethodName: "GetRunnableRunbookSteps",
			Handler:    _Runbooks_GetRunnableRunbookSteps_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runbooks.proto",
}
