// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by ./generator. DO NOT EDIT.
package dynrpcserver

import (
	"context"
	"sync"

	runbooks "github.com/hashicorp/terraform/internal/rpcapi/terraform1/runbooks"
)

type Runbooks struct {
	impl runbooks.RunbooksServer
	mu   sync.RWMutex
	runbooks.UnimplementedRunbooksServer
}

var _ runbooks.RunbooksServer = (*Runbooks)(nil)

func NewRunbooksStub() *Runbooks {
	return &Runbooks{}
}

func (s *Runbooks) CloseRunbookConfiguration(a0 context.Context, a1 *runbooks.CloseRunbookConfiguration_Request) (*runbooks.CloseRunbookConfiguration_Response, error) {
	impl, err := s.realRPCServer()
	if err != nil {
		return nil, err
	}
	return impl.CloseRunbookConfiguration(a0, a1)
}

func (s *Runbooks) ExecuteRunbookStep(a0 context.Context, a1 *runbooks.ExecuteRunbookStep_Request) (*runbooks.ExecuteRunbookStep_Response, error) {
	impl, err := s.realRPCServer()
	if err != nil {
		return nil, err
	}
	return impl.ExecuteRunbookStep(a0, a1)
}

func (s *Runbooks) FindRunbookConfigurationSteps(a0 context.Context, a1 *runbooks.FindRunbookConfigurationSteps_Request) (*runbooks.FindRunbookConfigurationSteps_Response, error) {
	impl, err := s.realRPCServer()
	if err != nil {
		return nil, err
	}
	return impl.FindRunbookConfigurationSteps(a0, a1)
}

func (s *Runbooks) GetRunnableRunbookSteps(a0 context.Context, a1 *runbooks.GetRunnableRunbookSteps_Request) (*runbooks.GetRunnableRunbookSteps_Response, error) {
	impl, err := s.realRPCServer()
	if err != nil {
		return nil, err
	}
	return impl.GetRunnableRunbookSteps(a0, a1)
}

func (s *Runbooks) OpenRunbookConfiguration(a0 context.Context, a1 *runbooks.OpenRunbookConfiguration_Request) (*runbooks.OpenRunbookConfiguration_Response, error) {
	impl, err := s.realRPCServer()
	if err != nil {
		return nil, err
	}
	return impl.OpenRunbookConfiguration(a0, a1)
}

func (s *Runbooks) PlanRunbookStep(a0 context.Context, a1 *runbooks.PlanRunbookStep_Request) (*runbooks.PlanRunbookStep_Response, error) {
	impl, err := s.realRPCServer()
	if err != nil {
		return nil, err
	}
	return impl.PlanRunbookStep(a0, a1)
}

func (s *Runbooks) ValidateRunbookConfiguration(a0 context.Context, a1 *runbooks.ValidateRunbookConfiguration_Request) (*runbooks.ValidateRunbookConfiguration_Response, error) {
	impl, err := s.realRPCServer()
	if err != nil {
		return nil, err
	}
	return impl.ValidateRunbookConfiguration(a0, a1)
}

func (s *Runbooks) ActivateRPCServer(impl runbooks.RunbooksServer) {
	s.mu.Lock()
	s.impl = impl
	s.mu.Unlock()
}

func (s *Runbooks) realRPCServer() (runbooks.RunbooksServer, error) {
	s.mu.RLock()
	impl := s.impl
	s.mu.RUnlock()
	if impl == nil {
		return nil, unavailableErr
	}
	return impl, nil
}
